version: "3.9"

services:
  muticket-ui:
    image: stesgroup/hod-portal:latest
    container_name: hod-portal-ui
    ports:
      - "3006:3000"
    environment:
      NODE_ENV: production
      NEXT_PUBLIC_API_URL: http://41.186.188.74:2000
    restart: unless-stopped
